
exports.seed = async function (knex) {
    // Deletes ALL existing entries
    await knex('product').del();
    await knex('product').insert([
      {
        id: 1,
        user_id: 1,
        category_id: 1,
        product_name: "Dining Table With Six Chairs",
        description: "Discover our brand new dining table set, available for sale at an incredibly low price! This 7-piece dining set includes a dining table and chairs. With the option of cash on delivery, purchasing is made easy. Kindly drop us a message for additional information. Please note that the price mentioned above only covers delivery charges.",
        interchangeable: "yes",
        price: 22,
        image_url: "http://localhost:8080/images/image_1.jpg",
      },
      {
        id: 2,
        user_id: 1,
        category_id: 1,
        product_name: "Dual Tio permanent Art Markers for Coloring",
        description: "Introducing the latest addition to our collection - brand new markers! These dual tip permanent art markers come in a set of 36/4860/80/120 colors, perfect for coloring, illustrations, and sketching. Whether you're a kid or an adult, these markers are sure to bring your artwork to life. Ideal for book painting, these markers offer vibrant and long-lasting colors.",
        interchangeable: "yes",
        price: 42,
        image_url: "http://localhost:8080/images/image_2.jpg",
      },
      {
        id: 3,
        user_id: 1,
        category_id: 3,
        product_name: "Children's Ferrari Ride on",
        description: "Looking for a thrilling ride for your little one? We have a Ferrari ride-on car available, which may be used but still in good condition. Despite a few scratches, it remains in excellent shape. Please note that one rim is missing. To enhance the experience, the ride-on comes with a remote control.",
        interchangeable: "yes",
        price: 77,
        image_url: "http://localhost:8080/images/image_3.jpg",
      },
      {
        id: 4,
        user_id: 2,
        category_id: 2,
        product_name: "Luxury Sectional Sofa",
        description: "Indulge in luxury with our special sale on velvet tufts sectional sofas. These sofas are available in a variety of designs and colors, ensuring there's a perfect match for your style and taste. Experience ultimate comfort and elegance in your living space with these exquisite pieces.",
        interchangeable: "no",
        price: 20,
        image_url: "http://localhost:8080/images/image_4.jpg",
      },
      {
        id: 5,
        user_id: 2,
        category_id: 2,
        product_name: "Metal Wall Art",
        description: "Enhance your wall decor with this beautiful handcrafted metal art piece. Its lovely soothing tones of gold finish create an enchanting ambiance. This wall art comes in one piece, ready and easy to hang on your wall. Elevate the aesthetic appeal of your space with this captivating addition.",
        interchangeable: "no",
        price: 25,
        image_url: "http://localhost:8080/images/image_5.jpg",
      },
      {
        id: 6,
        user_id: 3,
        category_id: 2,
        product_name: "Night Stands",
        description: "Add a touch of elegance to your bedroom with these two barely used, neat, and clean wooden nightstands. They are not only functional but also enhance the overall look of your bedroom. Each nightstand is priced at $99, but if you buy both together, you can get them for a discounted price of $175. Rest assured, they come from a pet-free and non-smoking home. The dimensions are as follows: Depth: 16 inches, Breadth: 22 inches, Height: 23 inches",
        interchangeable: "no",
        price: 30,
        image_url: "http://localhost:8080/images/image_6.jpg",
      },
      {
        id: 7,
        user_id: 3,
        category_id: 3,
        product_name: "Pull Out Sofa Bed",
        description: "Looking for a versatile and comfortable seating option? We have a brand new 3-seater pull out sofa bed available for sale. This sofa bed provides the perfect solution for accommodating guests while adding style to your living space.",
        interchangeable: "yes",
        price: 45,
        image_url: "http://localhost:8080/images/image_7.jpg",
      },
      {
        id: 8,
        user_id: 4,
        category_id: 3,
        product_name: "Three Piece Abstract Wall Art",
        description: "Immerse yourself in the world of modern art with this like-new 3-piece abstract canvas art. These three separate canvases can be arranged in various configurations, allowing you to create a dynamic and visually striking display. The dimensions of each panel are 40 x 60.",
        interchangeable: "yes",
        price: 86,
        image_url: "http://localhost:8080/images/image_8.jpg",
      },
      {
        id: 9,
        user_id: 5,
        category_id: 3,
        product_name: "Trampoline",
        description: "Looking for a trampoline that is suitable for both adults and kids? Look no further! This trampoline is in pristine condition, rated 10/10. It has been primarily used for workouts, ensuring its durability and reliability. Unfortunately, I am selling it due to an upcoming move. Don't miss out on this fantastic opportunity to bring fun and fitness into your home!",
        interchangeable: "no",
        price: 105,
        image_url: "http://localhost:8080/images/image_9.jpg",
      },
      {
        id: 10,
        user_id: 5,
        category_id: 3,
        product_name: "Washer Dryer Stainless Steel",
        description: "Like-new Samsung electric front load washer and dryer set in perfect working order. This 2019 Black Stainless Steel Platinum Series pair is exceptionally clean and offers all necessary options. Stackable and available for $950 pick-up or $1000 with delivery (no basement). Firm price, no offers below asking. Model numbers in pictures. Delivery limited to driveway or garage. Dimensions: 27 wide, 33 deep, 38 high (or 79 stacked). Upgrade your laundry care with this high-quality set.",
        interchangeable: "yes",
        price: 450,
        image_url: "http://localhost:8080/images/image_10.jpg",
      },
    ]);
  };